# Generated by Django 4.1.7 on 2023-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='reading_time',
            field=models.CharField(max_length=60),
        ),
    ]
